SELECT 
    EXTRACT(YEAR FROM STR_TO_DATE(ORDER_DATE, '%d-%m-%y')) AS ORDER_YEAR,
    EXTRACT(MONTH FROM STR_TO_DATE(ORDER_DATE, '%d-%m-%y')) AS ORDER_MONTH,
    SUM(QUANTITY * SALES) AS REVENUE,
    COUNT(DISTINCT ORDER_ID) AS VOLUME
FROM SUPERSTORE
GROUP BY ORDER_YEAR, ORDER_MONTH
ORDER BY ORDER_YEAR DESC, ORDER_MONTH DESC
LIMIT 6